services:
  - type: web
    name: saimjr-frontend
    env: node
    runtime: node-20.17.0
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_WS_URL
        sync: false
    healthCheckPath: /
    disk:
      name: saimjr-frontend-disk
      size: 1GB
      mountPath: /app/disk